title: EAVR
description: EAVR is a community for Effective Altruists interested or involved in VR
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
